<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Version>1.5.0</Version>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>QuickMediaIngest.Desktop</RootNamespace>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\QuickMediaIngest.Core\QuickMediaIngest.Core.csproj" />
    <ProjectReference Include="..\QuickMediaIngest.Localization\QuickMediaIngest.Localization.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.2" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="..\QuickMediaIngest\Assets\AppIcon.png" Link="Assets/AppIcon.png" />
  </ItemGroup>
  <ItemGroup>
    <TrimmerRootAssembly Include="Magick.NET-Q16-AnyCPU" />
    <TrimmerRootAssembly Include="Magick.NET.Core" />
    <TrimmerRootAssembly Include="NetVips" />
    <TrimmerRootAssembly Include="QuickMediaIngest.Core" />
  </ItemGroup>
</Project>
